### PR TITLE
Repo Cleanup and Reorg

### PR DESCRIPTION
**Pull request by pckilgore**
Finally removed a lot of old comments and logs, refactored some files to remove old/unused code, and tried to improve organization of the giant `components` folder.

There a lot of stuff here.  Let me know if you have any questions.  It all appears to work just fine based on testing.

### CODE REVIEW

**Comment by pckilgore** [comment]
@brenmeyer2245  OK?

**Comment by brenmeyer2245** [comment]
You got rid of the 20 <br/>'s?????
Lol. Looks great. Thanks!

**Comment by pckilgore** [comment]
Yeah, I fixed the styles a long time ago and forgot about it.  Thanks gents.

**Comment by pckilgore** [comment]
Cleanup and reorganization.

**Pull request merged**
